### ISSUE TITLE
client.futures_account_balance() problem

### ISSUE THREAD

**Issue by badosanjos** [LUCIT-Systems-and-Development/unicorn-binance-rest-api#76] opened 2023-08-09 02:25 UTC
### Solution to Issue cannot be found in the documentation or other Issues and also occurs in the latest version of this library.

- [X] I checked the documentation and other Issues. I am using the latest version of this library.

### Issue

Hi,
  The library is not adjusted for the change bellow and errors like this are appearing (APIError(code=-5000): GET /fapi/v1/positionRisk is retired, please use GET /fapi/v2/positionRisk)
  
2023-06-28

Notice:

REST

The following endpoints will no longer be supported from 2023-07-15:
GET /fapi/v1/account
GET /fapi/v1/balance
GET /fapi/v1/positionRisk
Please switch to corresponding v2 endpoints:
GET /fapi/v2/account
GET /fapi/v2/balance
GET /fapi/v2/positionRisk

**Comment by oliver-zehentleitner** [comment] 2024-02-16 19:48
I moved it to UBRA repository! Thank for the fix, i will implement it asap.

**Comment by oliver-zehentleitner** [comment] 2024-05-09 16:09
fixed!

Duplicate of https://github.com/LUCIT-Systems-and-Development/unicorn-binance-rest-api/issues/65

**Closed by oliver-zehentleitner** 2024-05-09 16:09 UTC
Labels: bug
